.TH INTLTOOL-MERGE 8 "February 04, 2002" "intltool"

.SH NAME
intltool-merge \- merge translated strings into various file 
types such as XML

.SH SYNOPSIS
.B "intltool-merge"
[
.BR \-b | --ba-style
] [
.BR \-d | --desktop-style
] [
.BR \-k | --keys-style
] [
.BR \-x | --xml-style
] [
.BR \-u | --utf8
] [
.BR \-p | --pass-through
] [
.BR \-q | --quiet
] [
.BR --help
] [
.BR --version
]
.IR PO_DIRECTORY
.IR FILENAME
.IR OUTPUT_FILE


.SH DESCRIPTION
Merge translated strings in po files in \fIPO_DIRECTORY\fP 
with the original application file \fIFILENAME\fP, 
and output the file \fIOUTPUT_FILE\fP containing both the original
and the localized strings.


.SH OPTIONS
.TP
.B \-b, \--ba-style
Includes translations in the bonobo-activation style
.TP
.B \-d, \--desktop-style
Includes translations in the desktop style
.TP
.B \-k, \--keys-style
Includes translations in the keys style
.TP
.B \-k, \--xml-style
Includes translations in the standard xml style
.TP
.B \-u, \--utf8
Convert all strings to UTF-8 before merging
.TP
.B \-p, \--pass-through
Use strings as found in .po files, without conversion (STRONGLY unrecommended with -x)
.TP
.B \-q, \--quiet
Suppress most messages
.TP
.B \--help
Display this help and exit
.TP
.B \--version
Output version information and exit

.SH REPORTING BUGS
Report bugs to http://bugzilla.gnome.org, module intltool, or by sending email
to xml-i18n-tools@gnome.org.

.SH AUTHOR
Darin Adler           <darin@bentspoon.com>
.br
Kenneth Christiansen  <kenneth@gnu.org>
.br
Maciej Stachowiak     <mjs@eazel.com>


.SH SEE ALSO
intltoolize(8), xml-18n-prepare(8), intltool-extract(8)
